### ISSUE TITLE
Link Tải về

### ISSUE THREAD

**Issue by Khang5687** [teefan/keep-talking-and-nobody-explodes-vi#1]
Cho tôi xin link tải về đc ko bro

**Comment by teefan** [comment]
Mình in ra PDF giùm bạn nè: https://drive.google.com/file/d/127CWtQgLBwQocViVaByjwsH7fmhnHHcI/view?usp=sharing

**Comment by Khang5687** [comment]
Cảm ơn bạn nhiều :3 À mà bạn mở link sharing đi bạn để có người sau cần sẽ tải đc :p
p/s: đáng lẽ là reply và close cái issue này sớm hơn nhưng hồi nãy github bị lỗi 500 :))
